Python 2->3 change, unlimit open files.
Change "workon" to use Python 3 environment.  Change shell soft limit for number of process open files to unlimited.

diff --git a/system_config/init/sgd-backend b/system_config/init/sgd-backend
--- a/system_config/init/sgd-backend
+++ b/system_config/init/sgd-backend
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          SGDBackend
 # Required-Start:    $network $named
@@ -13,25 +13,25 @@ PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 PIDFILE="/var/run/pyramid/backend.pid"
 
 if [ ! -d /var/run/pyramid ]; then
-        /bin/mkdir -p /var/run/pyramid
-        /bin/chown -R deploy:deploy /var/run/pyramid
+	/bin/mkdir -p /var/run/pyramid
+	/bin/chown -R deploy:deploy /var/run/pyramid
 fi
 
 case "$1" in
     start)
-        /bin/su deploy -c "cd /data/www/SGDBackend-NEX2/current && export WORKON_HOME=/data/envs/ && source virtualenvwrapper.sh && workon sgd && . prod_variables.sh && /usr/bin/make run-prod"
-        ;;
+	/bin/su deploy -c "ulimit -S -n unlimited; cd /data/www/SGDBackend-NEX2/current && export WORKON_HOME=/data/envs/ && source virtualenvwrapper.sh && workon sgd3 && . prod_variables.sh && /usr/bin/make run-prod"
+	;;
     stop)
-        /bin/kill `/bin/cat $PIDFILE`
-        if [ $? -eq 0 ]; then
-                /bin/rm $PIDFILE
-        else
-                echo "Error stopping SGDBackend"
-                exit 1
-        fi
-        ;;
+	/bin/kill `/bin/cat $PIDFILE`
+	if [ $? -eq 0 ]; then
+		/bin/rm $PIDFILE
+	else
+		echo "Error stopping SGDBackend"
+		exit 1
+	fi
+	;;
   *)
-        echo "Usage: $0 {start|stop}" >&2
-        exit 1
-        ;;
+	echo "Usage: $0 {start|stop}" >&2
+	exit 1
+	;;
 esac
